name: devin_api
description: A Dart client library for the Devin API.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: none

resolution: workspace

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  http: ^1.2.0
  meta: ^1.16.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mocktail: ^1.0.2
